In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/encuesta.csv")

print("Filas y columnas:")
print(df.shape)

print("\nInformación:")
print(df.info())

print("\nValores faltantes:")
print(df.isnull().sum())

Filas y columnas:
(82, 27)

Información:
<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 27 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   ID                                                           82 non-null     int64
 1   Tu Semestre Actual                                           82 non-null     str
 2   Eres originario de Guadalupe Victoria?                       82 non-null     str
 3   El Tecnológico de los Llanos fue tu:                         82 non-null     str
 4   ¿Por qué elegiste esta institución? (elige máximo 3)         82 non-null     str
 5   Si no fue tu primera opción, ¿cuál fue el motivo principal?  82 non-null     str
 6   Ingeniería Mecatrónica fue tu:                               82 non-null     str
 7   Motivo principal para elegir Mecatrónica                     82 non-null     str
 8   Antes de ingresar, tu conocimiento sobre la carrera era:     82 non-null     str
 9   Percepcion de Calidad académica general de la carrera        82 non-null     str
 10  Como consideras el nivel de los docentes                     82 non-null     str
 11  Preparación técnica que estás recibiendo                     82 non-null     str
 12  Actualización tecnológica de contenidos                      82 non-null     str
 13  Uso de laboratorios y prácticas                              82 non-null     str
 14  Vinculación con industria                                    82 non-null     str
 15  ¿Qué deberían mejorar los docentes? (máximo 2)               82 non-null     str
 16  Como sientes el Nivel de exigencia académica actual:         82 non-null     str
 17  Participación en concursos de robótica/tecnología            82 non-null     str
 18  Participación en proyectos de investigación                  82 non-null     str
 19  Que tan importante es para ti los Deportes institucionales   81 non-null     str
 20  Que tan importante es para ti las Actividades culturales     82 non-null     str
 21  Que tan importante es para ti los Clubes estudiantiles       82 non-null     str
 22  ¿Has participado en alguna actividad extracurricular?        82 non-null     str
 23  Si no participas, el motivo principal es:                    44 non-null     str
 24  ¿Has pensado en dejar la carrera?                            64 non-null     str
 25  Motivos que podrían llevarte a dejar la carrera (máximo 3):  82 non-null     str
 26  Nivel de satisfacción general con la carrera:                82 non-null     str
dtypes: int64(1), str(26)
memory usage: 44.7 KB
None

Valores faltantes:
ID                                                              0
Tu Semestre Actual                                              0
Eres originario de Guadalupe Victoria?                          0
El Tecnológico de los Llanos fue tu:                            0
¿Por qué elegiste esta institución? (elige máximo 3)            0
Si no fue tu primera opción, ¿cuál fue el motivo principal?     0
Ingeniería Mecatrónica fue tu:                                  0
Motivo principal para elegir Mecatrónica                        0
Antes de ingresar, tu conocimiento sobre la carrera era:        0
Percepcion de Calidad académica general de la carrera           0
Como consideras el nivel de los docentes                        0
Preparación técnica que estás recibiendo                        0
Actualización tecnológica de contenidos                         0
Uso de laboratorios y prácticas                                 0
Vinculación con industria                                       0
¿Qué deberían mejorar los docentes? (máximo 2)                  0
Como sientes el Nivel de exigencia académica actual:            0
Participación en concursos de robótica/tecnología               0
Participación en proyectos de investigación                     0
Que tan importante es para ti los Deportes institucionales      1
Que tan importante es para ti las Actividades culturales        0
Que tan importante es para ti los Clubes estudiantiles          0
¿Has participado en alguna actividad extracurricular?           0
Si no participas, el motivo principal es:                      38
¿Has pensado en dejar la carrera?                              18
Motivos que podrían llevarte a dejar la carrera (máximo 3):     0
Nivel de satisfacción general con la carrera:                   0
dtype: int64

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/encuesta.csv")

print("Filas y columnas:", df.shape)

df.head()

Filas y columnas: (82, 27)

,ID,Tu Semestre Actual,Eres originario de Guadalupe Victoria?,El Tecnológico de los Llanos fue tu:,¿Por qué elegiste esta institución? (elige máximo 3),"Si no fue tu primera opción, ¿cuál fue el motivo principal?",Ingeniería Mecatrónica fue tu:,Motivo principal para elegir Mecatrónica,"Antes de ingresar, tu conocimiento sobre la carrera era:",Percepcion de Calidad académica general de la carrera,...,Participación en concursos de robótica/tecnología,Participación en proyectos de investigación,Que tan importante es para ti los Deportes institucionales,Que tan importante es para ti las Actividades culturales,Que tan importante es para ti los Clubes estudiantiles,¿Has participado en alguna actividad extracurricular?,"Si no participas, el motivo principal es:",¿Has pensado en dejar la carrera?,Motivos que podrían llevarte a dejar la carrera (máximo 3):,Nivel de satisfacción general con la carrera:
0,1,8°,Si,2da opcion,Cercanía a mi domicilio;Recomendación de famil...,Decisión familiar,1er opción,Interés en Electrónica,Poco Claro,Buena,...,Importante,Algo Importante,Algo Importante,Importante,Importante,Si,NaN,Una vez,Falta de motivación,Satisfecho
1,2,8°,No,1er opcion,Cercanía a mi domicilio;Costo accesible;Recome...,No aplica,2da opción,Campo laboral ampli,Poco Claro,Buena,...,Importante,Algo Importante,Algo Importante,Algo Importante,Muy Importante,No,NaN,NaN,Estrés o carga excesiva,Satisfecho
2,3,8°,No,1er opcion,Cercanía a mi domicilio;Recomendación de famil...,No aplica,1er opción,Interés en Electrónica,Poco Claro,Buena,...,Importante,Muy Importante,Importante,Muy Importante,Importante,Si,NaN,Nunca,Problemas económicos,Satisfecho
3,4,8°,No,2da opcion,Cercanía a mi domicilio;,Cambié de interes,1er opción,Interés en Robótica,Poco Claro,Excelente,...,Importante,Importante,Algo Importante,Algo Importante,Importante,No,NaN,NaN,Problemas personales,Satisfecho
4,5,8°,Si,3er opción o más,Otra;,Motivos económicos,1er opción,Interés en Electrónica,Muy Limitado,Buena,...,Muy Importante,Muy Importante,Importante,Importante,Importante,Si,NaN,Nunca,Cambio de intereses,Neutral

In [4]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 27 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   ID                                                           82 non-null     int64
 1   Tu Semestre Actual                                           82 non-null     str
 2   Eres originario de Guadalupe Victoria?                       82 non-null     str
 3   El Tecnológico de los Llanos fue tu:                         82 non-null     str
 4   ¿Por qué elegiste esta institución? (elige máximo 3)         82 non-null     str
 5   Si no fue tu primera opción, ¿cuál fue el motivo principal?  82 non-null     str
 6   Ingeniería Mecatrónica fue tu:                               82 non-null     str
 7   Motivo principal para elegir Mecatrónica                     82 non-null     str
 8   Antes de ingresar, tu conocimiento sobre la carrera era:     82 non-null     str
 9   Percepcion de Calidad académica general de la carrera        82 non-null     str
 10  Como consideras el nivel de los docentes                     82 non-null     str
 11  Preparación técnica que estás recibiendo                     82 non-null     str
 12  Actualización tecnológica de contenidos                      82 non-null     str
 13  Uso de laboratorios y prácticas                              82 non-null     str
 14  Vinculación con industria                                    82 non-null     str
 15  ¿Qué deberían mejorar los docentes? (máximo 2)               82 non-null     str
 16  Como sientes el Nivel de exigencia académica actual:         82 non-null     str
 17  Participación en concursos de robótica/tecnología            82 non-null     str
 18  Participación en proyectos de investigación                  82 non-null     str
 19  Que tan importante es para ti los Deportes institucionales   81 non-null     str
 20  Que tan importante es para ti las Actividades culturales     82 non-null     str
 21  Que tan importante es para ti los Clubes estudiantiles       82 non-null     str
 22  ¿Has participado en alguna actividad extracurricular?        82 non-null     str
 23  Si no participas, el motivo principal es:                    44 non-null     str
 24  ¿Has pensado en dejar la carrera?                            64 non-null     str
 25  Motivos que podrían llevarte a dejar la carrera (máximo 3):  82 non-null     str
 26  Nivel de satisfacción general con la carrera:                82 non-null     str
dtypes: int64(1), str(26)
memory usage: 44.7 KB
None

In [5]:
faltantes = df.isnull().sum()

print(faltantes)

ID                                                              0
Tu Semestre Actual                                              0
Eres originario de Guadalupe Victoria?                          0
El Tecnológico de los Llanos fue tu:                            0
¿Por qué elegiste esta institución? (elige máximo 3)            0
Si no fue tu primera opción, ¿cuál fue el motivo principal?     0
Ingeniería Mecatrónica fue tu:                                  0
Motivo principal para elegir Mecatrónica                        0
Antes de ingresar, tu conocimiento sobre la carrera era:        0
Percepcion de Calidad académica general de la carrera           0
Como consideras el nivel de los docentes                        0
Preparación técnica que estás recibiendo                        0
Actualización tecnológica de contenidos                         0
Uso de laboratorios y prácticas                                 0
Vinculación con industria                                       0
¿Qué deberían mejorar los docentes? (máximo 2)                  0
Como sientes el Nivel de exigencia académica actual:            0
Participación en concursos de robótica/tecnología               0
Participación en proyectos de investigación                     0
Que tan importante es para ti los Deportes institucionales      1
Que tan importante es para ti las Actividades culturales        0
Que tan importante es para ti los Clubes estudiantiles          0
¿Has participado en alguna actividad extracurricular?           0
Si no participas, el motivo principal es:                      38
¿Has pensado en dejar la carrera?                              18
Motivos que podrían llevarte a dejar la carrera (máximo 3):     0
Nivel de satisfacción general con la carrera:                   0
dtype: int64

In [6]:
duplicados = df.duplicated().sum()

print("Duplicados encontrados:", duplicados)

Duplicados encontrados: 0

In [7]:
calidad = pd.DataFrame({
    "Valores Faltantes": df.isnull().sum(),
    "Tipo de Dato": df.dtypes
})

calidad

,Valores Faltantes,Tipo de Dato
ID,0,int64
Tu Semestre Actual,0,str
Eres originario de Guadalupe Victoria?,0,str
El Tecnológico de los Llanos fue tu:,0,str
¿Por qué elegiste esta institución? (elige máximo 3),0,str
"Si no fue tu primera opción, ¿cuál fue el motivo principal?",0,str
Ingeniería Mecatrónica fue tu:,0,str
Motivo principal para elegir Mecatrónica,0,str
"Antes de ingresar, tu conocimiento sobre la carrera era:",0,str
Percepcion de Calidad académica general de la carrera,0,str
Como consideras el nivel de los docentes,0,str
Preparación técnica que estás recibiendo,0,str
Actualización tecnológica de contenidos,0,str
Uso de laboratorios y prácticas,0,str
Vinculación con industria,0,str
¿Qué deberían mejorar los docentes? (máximo 2),0,str
Como sientes el Nivel de exigencia académica actual:,0,str
Participación en concursos de robótica/tecnología,0,str
Participación en proyectos de investigación,0,str
Que tan importante es para ti los Deportes institucionales,1,str
Que tan importante es para ti las Actividades culturales,0,str
Que tan importante es para ti los Clubes estudiantiles,0,str
¿Has participado en alguna actividad extracurricular?,0,str
"Si no participas, el motivo principal es:",38,str
¿Has pensado en dejar la carrera?,18,str
Motivos que podrían llevarte a dejar la carrera (máximo 3):,0,str
Nivel de satisfacción general con la carrera:,0,str

In [8]:
df_limpio = df.copy()

print("Copia creada correctamente")

Copia creada correctamente

In [9]:
df.isnull().sum()[df.isnull().sum() > 0]

Que tan importante es para ti los Deportes institucionales     1
Si no participas, el motivo principal es:                     38
¿Has pensado en dejar la carrera?                             18
dtype: int64

In [13]:
for col in df.columns:
    if df[col].dtype == "object":
        print("\n====================")
        print(col)
        print(df[col].dropna().unique()[:20])

In [11]:
registro_cambios = []

In [14]:
print(df.columns)

Index(['ID', 'Tu Semestre Actual', 'Eres originario de Guadalupe Victoria?',
       'El Tecnológico de los Llanos fue tu:',
       '¿Por qué elegiste esta institución? (elige máximo 3)',
       'Si no fue tu primera opción, ¿cuál fue el motivo principal?',
       'Ingeniería Mecatrónica fue tu:',
       'Motivo principal para elegir Mecatrónica ',
       'Antes de ingresar, tu conocimiento sobre la carrera era:',
       'Percepcion de Calidad académica general de la carrera',
       'Como consideras el nivel de los docentes',
       'Preparación técnica que estás recibiendo',
       'Actualización tecnológica de contenidos',
       'Uso de laboratorios y prácticas', 'Vinculación con industria',
       '¿Qué deberían mejorar los docentes? (máximo 2)',
       'Como sientes el Nivel de exigencia académica actual:',
       'Participación en concursos de robótica/tecnología',
       'Participación en proyectos de investigación',
       'Que tan importante es para ti los Deportes institucionales',
       'Que tan importante es para ti las Actividades culturales',
       'Que tan importante es para ti los Clubes estudiantiles ',
       '¿Has participado en alguna actividad extracurricular?',
       'Si no participas, el motivo principal es:',
       '¿Has pensado en dejar la carrera?',
       'Motivos que podrían llevarte a dejar la carrera (máximo 3):',
       'Nivel de satisfacción general con la carrera:'],
      dtype='str')

In [15]:
print(df.select_dtypes(include="object").columns)

Index(['Tu Semestre Actual', 'Eres originario de Guadalupe Victoria?',
       'El Tecnológico de los Llanos fue tu:',
       '¿Por qué elegiste esta institución? (elige máximo 3)',
       'Si no fue tu primera opción, ¿cuál fue el motivo principal?',
       'Ingeniería Mecatrónica fue tu:',
       'Motivo principal para elegir Mecatrónica ',
       'Antes de ingresar, tu conocimiento sobre la carrera era:',
       'Percepcion de Calidad académica general de la carrera',
       'Como consideras el nivel de los docentes',
       'Preparación técnica que estás recibiendo',
       'Actualización tecnológica de contenidos',
       'Uso de laboratorios y prácticas', 'Vinculación con industria',
       '¿Qué deberían mejorar los docentes? (máximo 2)',
       'Como sientes el Nivel de exigencia académica actual:',
       'Participación en concursos de robótica/tecnología',
       'Participación en proyectos de investigación',
       'Que tan importante es para ti los Deportes institucionales',
       'Que tan importante es para ti las Actividades culturales',
       'Que tan importante es para ti los Clubes estudiantiles ',
       '¿Has participado en alguna actividad extracurricular?',
       'Si no participas, el motivo principal es:',
       '¿Has pensado en dejar la carrera?',
       'Motivos que podrían llevarte a dejar la carrera (máximo 3):',
       'Nivel de satisfacción general con la carrera:'],
      dtype='str')

C:\Users\estup\AppData\Local\Temp\ipykernel_37812\1199234879.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns)

In [16]:
print(df.select_dtypes(include="object").columns)

Index(['Tu Semestre Actual', 'Eres originario de Guadalupe Victoria?',
       'El Tecnológico de los Llanos fue tu:',
       '¿Por qué elegiste esta institución? (elige máximo 3)',
       'Si no fue tu primera opción, ¿cuál fue el motivo principal?',
       'Ingeniería Mecatrónica fue tu:',
       'Motivo principal para elegir Mecatrónica ',
       'Antes de ingresar, tu conocimiento sobre la carrera era:',
       'Percepcion de Calidad académica general de la carrera',
       'Como consideras el nivel de los docentes',
       'Preparación técnica que estás recibiendo',
       'Actualización tecnológica de contenidos',
       'Uso de laboratorios y prácticas', 'Vinculación con industria',
       '¿Qué deberían mejorar los docentes? (máximo 2)',
       'Como sientes el Nivel de exigencia académica actual:',
       'Participación en concursos de robótica/tecnología',
       'Participación en proyectos de investigación',
       'Que tan importante es para ti los Deportes institucionales',
       'Que tan importante es para ti las Actividades culturales',
       'Que tan importante es para ti los Clubes estudiantiles ',
       '¿Has participado en alguna actividad extracurricular?',
       'Si no participas, el motivo principal es:',
       '¿Has pensado en dejar la carrera?',
       'Motivos que podrían llevarte a dejar la carrera (máximo 3):',
       'Nivel de satisfacción general con la carrera:'],
      dtype='str')

C:\Users\estup\AppData\Local\Temp\ipykernel_37812\1199234879.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns)

In [17]:
col_texto = df.select_dtypes(include="object").columns[0]

print("Columna:")
print(col_texto)

print("\nValores:")
print(df[col_texto].value_counts())

Columna:
Tu Semestre Actual

Valores:
Tu Semestre Actual
2°    24
4°    23
8°    18
6°    17
Name: count, dtype: int64

C:\Users\estup\AppData\Local\Temp\ipykernel_37812\658622066.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  col_texto = df.select_dtypes(include="object").columns[0]

In [18]:
df_limpio.to_csv(
    "../data/processed/encuesta_limpia.csv",
    index=False
)

print("Dataset limpio guardado correctamente")

Dataset limpio guardado correctamente

In [19]:
cambios = pd.DataFrame({
    "Problema": [
        "Valores faltantes",
        "Duplicados"
    ],
    "Accion": [
        "Reemplazo por etiquetas descriptivas",
        "Verificación"
    ],
    "Resultado": [
        "57 valores corregidos",
        "0 duplicados encontrados"
    ]
})

cambios

,Problema,Accion,Resultado
0,Valores faltantes,Reemplazo por etiquetas descriptivas,57 valores corregidos
1,Duplicados,Verificación,0 duplicados encontrados